{
    'name': 'Loan Management',
    'version': '1.0',
    'category': 'Finance',
    'summary': 'Manage employee loans and payroll deductions',
    'description': 'Module for managing loans, installments, and payroll deductionsaccount cost',
    'category': 'Accounting',
    'author': 'Happy Three Creation',
    'depends': ['base', 'hr_payroll'],
    'data': [
        'views/loan_view.xml',
        'views/loan_installment_view.xml',
        'views/loan_action.xml',
        'views/loan_menu.xml',
        'security/ir.model.access.csv',
    ],
    'icon:': ['static/description/icon.png'],
    'installable': True,
    'application': True,
}